---
title: 'Pre-service teachers’ perceived value of general pedagogical knowledge for
  practice: Relations with epistemic beliefs and source beliefs'
author: Jürgen Schneider
date: '2017-09-21'
slug: pre-service-teachers-perceived-value-of-general-pedagogical-knowledge
categories: []
tags: []
comments: no
images: ~
---

### Authors


* Samuel Merk 
* Tom Rosman
* Julia Rueß
* Marcus Syring
* Jürgen Schneider

### Abstract

Pre-service teachers tend to devalue general pedagogical knowledge (GPK) as a valid source for deriving successful teaching practices. The present study investigated beliefs about knowledge sources and epistemic beliefs as predictors for students’ perceived value of GPK. Three pre-registered hypotheses were tested. We expected beliefs that GPK originates from scientific sources to entail a devaluation of GPK (Hypothesis 1). Concerning epistemic beliefs, we expected absolute beliefs to positively, and multiplistic beliefs to negatively predict pre-service teachers’ perceived practical value of GPK (Hypothesis 2). Finally, we expected relationships between epistemic beliefs and pre-service teachers’ perceived practical value of GPK to be confounded by epistemic trustworthiness, perceived topic-specific consistency and topic-specific familiarity (Hypothesis 3). In a study using a split plot design, 365 pre-service teachers were presented with four texts on different educational research topics. For each topic, three text versions were constructed. Even though they were invariant in content, these versions varied in a way that the results were allegedly generated by a practitioner, an expert or by means of a scientific study. Unexpectedly, results showed that research findings allegedly generated by means of a scientific study were associated with a higher perceived value of (topic-specific) GPK for practice (Hypothesis 1). As expected, the perceived value of GPK for practice was predicted by topic-specific multiplism and domain-specific absolutism (Hypothesis 2). These predictive effects were confounded by expertise evaluations of the source and the consistency of prior beliefs with the presented research results (Hypothesis 3). In summary, our results suggest that source beliefs might not be responsible for the devaluation of GPK, but that beliefs on the nature and structure of GPK (i.e., epistemic beliefs) might play an even more important role in this respect. Implications for research and practice are discussed.
### Access to Paper

[Link to PDF](https://doi.org/10.1371/journal.pone.0184971).


### Citation

Merk, S., Rosman, T., Rueß, J., Syring, M., & Schneider, J. (2017). Pre-service teachers’ perceived value of general pedagogical knowledge for practice: Relations with epistemic beliefs and source beliefs. _PloS one, 12_(9), 0184971. https://doi.org/10.1371/journal.pone.0184971

