---
title: 'Relationierung von Theorie Und Praxis: Was Bedeutet Dieses Konzept Für Die
  Begleitung von Praktika in Der Lehrerinnen- Und Lehrerbildung?'
author: Jürgen Schneider
date: '2020-01-24'
slug: relationierung-von-theorie-und-praxis
categories: []
tags: []
comments: no
images: ~
---

### Authors

* Jürgen Schneider
* Colin Cramer

### Abstract

Im Beitrag wird das Konzept der Relationierung von Theorie und Praxis ausgehend vom strukturtheoretischen Professionsansatz diskutiert. Dabei wird das Konzept mit der Hybridität zweier Praxen verbunden und dessen Konsequenzen für die Lehrer*innenbildung werden nachgezeichnet. Im Sinne der Einlassung und Distanz auf beide Praxen eröffnet das Konzept eine konstruktive Perspektive auf den Umgang mit Wissenschaftspraxis und Schulpraxis im Rahmen der Qualifikation von Lehrpersonen – besonders in schulpraktischen Phasen.

### Access to Paper

[Link to PDF](https://www.pedocs.de/volltexte/2020/19032/pdf/Rheinlaender_Scholl_2020_Verlaengerte_Praxisphasen_in_der_Lehrer_innenbildung.pdf).


### Citation

Schneider, J., & Cramer, C. (2020). Relationierung von Theorie und Praxis: Was bedeutet dieses Konzept für die Begleitung von Praktika in der Lehrerinnen- und Lehrerbildung? In K. Rheinländer & D. Scholl (Hrsg.), _Verlängerte Praxisphasen in der universitären Lehrerbildung: Spannungsfelder zwischen Theorie, Praxis und der Bestimmung von Professionalisierung_ (S. 23–38). Klinkhardt.

